/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.ArrayList;

/**
 *
 * @author Maria
 */
public class CreateMap extends javax.swing.JFrame {

    private Store s1, s2, s3, s4, s5;
    private Road r1, r2, r3, r4;
    private ArrayList<Store> stores;
    private ArrayList<Road> roads;
        
    /**
     * Creates new form CreateMap
     */
    public CreateMap(ArrayList<Store> stores,ArrayList<Road> roads) {
        this.stores=stores;
        this.roads=roads;
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph1 = new test.Graph();
        btnCreateStores = new javax.swing.JButton();
        btnCreateRoads = new javax.swing.JButton();
        labelSuccessCreatedStores = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelSuccessCreatedRoads = new javax.swing.JLabel();

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setLocation(new java.awt.Point(500, 200));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                disableLabels(evt);
            }
        });

        btnCreateStores.setText("Create Stores");
        btnCreateStores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStoresActionPerformed(evt);
            }
        });

        btnCreateRoads.setText("Create Roads ");
        btnCreateRoads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRoadsActionPerformed(evt);
            }
        });

        labelSuccessCreatedStores.setForeground(new java.awt.Color(0, 153, 0));
        labelSuccessCreatedStores.setText("Stores have been created!");

        jLabel2.setText("What would you like to do?");

        labelSuccessCreatedRoads.setForeground(new java.awt.Color(0, 153, 0));
        labelSuccessCreatedRoads.setText("Roads have been created!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSuccessCreatedRoads)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnCreateStores))
                    .addComponent(labelSuccessCreatedStores)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCreateRoads)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnCreateStores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSuccessCreatedStores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateRoads)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSuccessCreatedRoads)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRoadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRoadsActionPerformed
        // TODO add your handling code here:
        r1 = new Road();
        r1.addNewRoad(s1, s2, graph1);

        r2 = new Road();
        r2.addNewRoad(s2, s3, graph1);

        r3 = new Road();
        r3.addNewRoad(s2, s4, graph1);

        r4 = new Road();
        r4.addNewRoad(s3, s5, graph1);
        
        roads.add(r1);
        roads.add(r2);
        roads.add(r3);
        roads.add(r4);
      
        
        labelSuccessCreatedRoads.setVisible(true);
       
    }//GEN-LAST:event_btnCreateRoadsActionPerformed

    private void btnCreateStoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStoresActionPerformed
        // TODO add your handling code here:
        
        s1 = new Store();
        s1.addNewStore("Store1", 100, 100, null,graph1);

        s2 = new Store();
        s2.addNewStore("Store2", 330, 240, s1, graph1);

        s3 = new Store();
        s3.addNewStore("Store3", 400, 50, s1, graph1);

        s4 = new Store();
        s4.addNewStore("Store4", 40, 300, s1, graph1);

        s5 = new Store();
        s5.addNewStore("Store5", 250, 50, s1, graph1);
        
        stores.add(s1);
        stores.add(s2);
        stores.add(s3);
        stores.add(s4);
        stores.add(s5);
    
        labelSuccessCreatedStores.setVisible(true);
       
    }//GEN-LAST:event_btnCreateStoresActionPerformed

    private void disableLabels(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_disableLabels
        // TODO add your handling code here:
        labelSuccessCreatedStores.setVisible(false);
        labelSuccessCreatedRoads.setVisible(false);
    }//GEN-LAST:event_disableLabels

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreateMap().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRoads;
    private javax.swing.JButton btnCreateStores;
    private test.Graph graph1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelSuccessCreatedRoads;
    private javax.swing.JLabel labelSuccessCreatedStores;
    // End of variables declaration//GEN-END:variables
}
