/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JPanel;

public class GUI extends javax.swing.JFrame {

    private ArrayList<Store> stores = new ArrayList<Store>();
    private ArrayList<Road> roads = new ArrayList<Road>();

    private Order o2, o3, o4, o5;
    private Store s1, s2, s3, s4, s5;
    private Road r1, r2, r3, r4;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph1 = new test.Graph();
        btnOrders = new javax.swing.JButton();
        btnRoads = new javax.swing.JButton();
        btnSendOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(565, 381));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                createStores(evt);
                createRoads(evt);
                createOrders(evt);
            }
        });

        graph1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnOrders.setText("Orders");
        btnOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdersActionPerformed(evt);
            }
        });

        btnRoads.setText("Roads");
        btnRoads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoadsActionPerformed(evt);
            }
        });

        btnSendOrders.setText("Send Orders");
        btnSendOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRoads, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrders, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(graph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnOrders)
                .addGap(18, 18, 18)
                .addComponent(btnRoads)
                .addGap(18, 18, 18)
                .addComponent(btnSendOrders)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdersActionPerformed

        OrdersView orders = new OrdersView(o2, o3, o4, o5);
        orders.show();
        orders.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);

    }//GEN-LAST:event_btnOrdersActionPerformed

    private void createStores(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createStores
        // TODO add your handling code here:
        s1 = new Store();
        s1.addNewStore("Store1", 100, 100, null, graph1);

        s2 = new Store();
        s2.addNewStore("Store2", 330, 240, s1, graph1);

        s3 = new Store();
        s3.addNewStore("Store3", 400, 50, s1, graph1);

        s4 = new Store();
        s4.addNewStore("Store4", 40, 300, s1, graph1);

        s5 = new Store();
        s5.addNewStore("Store5", 250, 50, s1, graph1);

        stores.add(s1);
        stores.add(s2);
        stores.add(s3);
        stores.add(s4);
        stores.add(s5);

        s1.drawStore();
        s2.drawStore();
        s3.drawStore();
        s4.drawStore();
        s5.drawStore();
    }//GEN-LAST:event_createStores

    private void createRoads(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createRoads
        // TODO add your handling code here:
        r1 = new Road();
        r1.addNewRoad(s1, s2, graph1);

        r2 = new Road();
        r2.addNewRoad(s2, s3, graph1);

        r3 = new Road();
        r3.addNewRoad(s2, s4, graph1);

        r4 = new Road();
        r4.addNewRoad(s3, s5, graph1);

        roads.add(r1);
        roads.add(r2);
        roads.add(r3);
        roads.add(r4);

        r1.drawRoad();
        r2.drawRoad();
        r3.drawRoad();
        r4.drawRoad();
    }//GEN-LAST:event_createRoads

    private void btnRoadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoadsActionPerformed
        // TODO add your handling code here:
        RoadsView roads = new RoadsView(r1, r2, r3, r4);
        roads.show();
        roads.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getSize().width) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - getSize().height) / 2);

    }//GEN-LAST:event_btnRoadsActionPerformed

    private void createOrders(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createOrders
        o2 = new Order();
        o2.addNewOrder(s2);

        o3 = new Order();
        o3.addNewOrder(s3);

        o4 = new Order();
        o4.addNewOrder(s4);

        o5 = new Order();
        o5.addNewOrder(s5);
    }//GEN-LAST:event_createOrders

    private void btnSendOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOrdersActionPerformed
        // TODO add your handling code here:
        SendOrders();

    }//GEN-LAST:event_btnSendOrdersActionPerformed

    /* Send the orders */
    private void SendOrders() {
        o2.sendOrder();
        o3.sendOrder();
        o4.sendOrder();
        o5.sendOrder();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrders;
    private javax.swing.JButton btnRoads;
    private javax.swing.JButton btnSendOrders;
    private test.Graph graph1;
    // End of variables declaration//GEN-END:variables

}
